services:
    _defaults:
        public: false
        autowire: true

    OxidAcademy\CategoryLogger\Event\EventSubscriber:
        class: OxidAcademy\CategoryLogger\Event\EventSubscriber
        tags: ['kernel.event_subscriber']
