services:
    _defaults:
        public: false
        autowire: true

    OxidAcademy\CategoryLogger\Event\LoggerEventSubscriber:
        class: OxidAcademy\CategoryLogger\Event\LoggerEventSubscriber
        tags: ['kernel.event_subscriber']
